version: '3.6'
services:
  iris:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    command: --check-caps false
    ports:
      - 1972
      - 32793:52773
      - 53773
    volumes:
      - ./:/home/irisowner/irisdev
